// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPAzBXPCwpAPaU56WmO9wNIoCHtGuLPVo',
    appId: '1:31284208271:web:ae2067405e6228778b46fa',
    messagingSenderId: '31284208271',
    projectId: 'flutter-ui-playground',
    authDomain: 'flutter-ui-playground.firebaseapp.com',
    storageBucket: 'flutter-ui-playground.firebasestorage.app',
    measurementId: 'G-GJ02CN07HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYa55D0tzpTF-gYenWLVCLefuZqMLUNkc',
    appId: '1:31284208271:android:d0bbc6bc1b3732bf8b46fa',
    messagingSenderId: '31284208271',
    projectId: 'flutter-ui-playground',
    storageBucket: 'flutter-ui-playground.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEECRb_0pwUBLZPXNUA1TJMxkBz6WZP-A',
    appId: '1:31284208271:ios:904c7cae588bdb9d8b46fa',
    messagingSenderId: '31284208271',
    projectId: 'flutter-ui-playground',
    storageBucket: 'flutter-ui-playground.firebasestorage.app',
    iosBundleId: 'com.ssk.flutterUiPlayground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEECRb_0pwUBLZPXNUA1TJMxkBz6WZP-A',
    appId: '1:31284208271:ios:904c7cae588bdb9d8b46fa',
    messagingSenderId: '31284208271',
    projectId: 'flutter-ui-playground',
    storageBucket: 'flutter-ui-playground.firebasestorage.app',
    iosBundleId: 'com.ssk.flutterUiPlayground',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPAzBXPCwpAPaU56WmO9wNIoCHtGuLPVo',
    appId: '1:31284208271:web:c9fd05ade0915a538b46fa',
    messagingSenderId: '31284208271',
    projectId: 'flutter-ui-playground',
    authDomain: 'flutter-ui-playground.firebaseapp.com',
    storageBucket: 'flutter-ui-playground.firebasestorage.app',
    measurementId: 'G-GT3CY8Q3HZ',
  );
}
